<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Iberia</name>
   <tag></tag>
   <elementGuidId>d4c8364a-1976-4dcd-81ef-78ffe110afdc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='highcharts-0']/div/div/div/div[11]/span/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8ffecbe4-9a49-46be-89a7-dd84d47692ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>legendmap-name</value>
      <webElementGuid>885eeee5-0519-47a7-880d-9cc62d64fb50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Iberia</value>
      <webElementGuid>ede5afd9-ef13-4634-b9de-75b02ebb4eb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;highcharts-0&quot;)/div[@class=&quot;highcharts-legend&quot;]/div[1]/div[1]/div[@class=&quot;highcharts-legend-item&quot;]/span[1]/div[@class=&quot;legendmap-item&quot;]/div[@class=&quot;legendmap-name&quot;]</value>
      <webElementGuid>9dad453d-eeb1-4ae2-85b5-72dfc9a0d86c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='highcharts-0']/div/div/div/div[11]/span/div/div</value>
      <webElementGuid>58aaf724-5000-4b57-b011-c1d1cf0f6c4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='M1-M2:'])[5]/following::div[3]</value>
      <webElementGuid>ab7ab360-fac4-4f44-bf6e-01b36f9a5913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='M3-M4:'])[6]/preceding::div[1]</value>
      <webElementGuid>93cb1e5c-b7c2-429f-ba0d-5c3100410494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='M5-M6:'])[2]/preceding::div[1]</value>
      <webElementGuid>5ef97ac9-4519-48f8-82fb-07bf4720ed0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/span/div/div</value>
      <webElementGuid>900f6c41-220e-4e55-8495-d2fdc9d644ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Iberia' or . = ' Iberia')]</value>
      <webElementGuid>ab7587fb-b219-47f9-8364-cbf58a50e73d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
