<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Iberia</name>
   <tag></tag>
   <elementGuidId>d4c8364a-1976-4dcd-81ef-78ffe110afdc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='highcharts-0']/div/div/div/div[11]/span/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f42c8742-b21a-48a8-b03f-b512ecd80823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>legendmap-name</value>
      <webElementGuid>e1cdee8e-bc60-46cd-ba57-a02135674f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Iberia</value>
      <webElementGuid>735012e7-eea7-4212-9658-9ff515580a04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;highcharts-0&quot;)/div[@class=&quot;highcharts-legend&quot;]/div[1]/div[1]/div[@class=&quot;highcharts-legend-item&quot;]/span[1]/div[@class=&quot;legendmap-item&quot;]/div[@class=&quot;legendmap-name&quot;]</value>
      <webElementGuid>ad5e58b8-475f-4eea-89ab-9770a34b5f17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='highcharts-0']/div/div/div/div[11]/span/div/div</value>
      <webElementGuid>026bdfb9-2d82-4c17-8c35-8e567aaa98e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='M1-M2:'])[5]/following::div[3]</value>
      <webElementGuid>89688d18-f09d-47a1-94dc-b815c8f76867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='M3-M4:'])[6]/preceding::div[1]</value>
      <webElementGuid>4cdda81d-fe9c-4d02-b9de-4ce109041000</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='M5-M6:'])[2]/preceding::div[1]</value>
      <webElementGuid>8fd1737c-876f-41ff-a7c7-62e32c66879a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/span/div/div</value>
      <webElementGuid>72318c0a-7acc-4267-a0a0-8ae1994314b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Iberia' or . = ' Iberia')]</value>
      <webElementGuid>d58899c4-3cc6-4e00-b9fa-1971335a6b49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
