<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_France</name>
   <tag></tag>
   <elementGuidId>8209f45f-e9ea-43b4-b7d8-0d70102249be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='highcharts-0']/div/div/div/div[7]/span/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e2471d5a-8f96-4161-8b8e-4a4389c433a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>legendmap-name</value>
      <webElementGuid>1bf9857b-1019-4093-b1b8-c8f3d3379d58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> France</value>
      <webElementGuid>c36744a7-6958-4080-a392-54a8ca24f0f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;highcharts-0&quot;)/div[@class=&quot;highcharts-legend&quot;]/div[1]/div[1]/div[@class=&quot;highcharts-legend-item&quot;]/span[1]/div[@class=&quot;legendmap-item&quot;]/div[@class=&quot;legendmap-name&quot;]</value>
      <webElementGuid>3b95fd78-02a6-4aee-a92e-6f0f7a49ca05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='highcharts-0']/div/div/div/div[7]/span/div/div</value>
      <webElementGuid>02103eaa-8715-4c5f-918a-689faf331869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='M3-M4:'])[3]/following::div[3]</value>
      <webElementGuid>0adecc78-970d-409d-bf10-f7593a75406f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='M1-M2:'])[4]/preceding::div[1]</value>
      <webElementGuid>9d09eb01-a823-489f-9930-aeec8d4b29e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='M3-M4:'])[4]/preceding::div[1]</value>
      <webElementGuid>3d9c559c-6b77-4ca1-8d44-fabf36bbb5df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/span/div/div</value>
      <webElementGuid>76c35d31-be09-4468-802f-c4039f06c526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' France' or . = ' France')]</value>
      <webElementGuid>d4c779a8-2a53-46fd-8cdd-9a77490388ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
