<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CP Almeria (ES)</name>
   <tag></tag>
   <elementGuidId>8bc73d40-f577-4f86-be64-3e99958a3425</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='sendForm(124);']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>22b3aea1-f579-46ca-abca-4dc909fc4398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>ec7e126e-02d2-49b1-b522-7b926f29826e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>sendForm(124);</value>
      <webElementGuid>feede2a6-5c19-4763-b6a8-affa64f1ccb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>decorate(this,0);</value>
      <webElementGuid>725600e7-1f6c-42ae-8c0d-f731e6e108e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>decorate(this,1);</value>
      <webElementGuid>9971a821-b3c5-48dd-9e88-0884d762cf90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CP Almeria (ES)</value>
      <webElementGuid>e09325bf-507a-4fba-8e44-b6dae2831aad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;m1&quot;)/div[@class=&quot;dealers-column&quot;]/div[@id=&quot;element-select2&quot;]/table[@id=&quot;dealerList&quot;]/tbody[1]/tr[1]/td[4]/a[1]</value>
      <webElementGuid>929ef543-1cd7-4951-8a17-dd99bc93e8a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='sendForm(124);']</value>
      <webElementGuid>1bcfec1d-1e2c-4370-95cb-d1bb4e108d77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//table[@id='dealerList']/tbody/tr/td[4]/a)[3]</value>
      <webElementGuid>467e3063-0a69-42dd-8a93-044dcbae0b7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'CP Almeria (ES)')]</value>
      <webElementGuid>3fe154fe-e7e9-4d8e-9dbb-5f2dc89aaaa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CP Alicante (ES)'])[1]/following::a[1]</value>
      <webElementGuid>efe5fb7d-9523-4e68-beed-427baf04d817</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CP A Coruña (ES)'])[1]/following::a[2]</value>
      <webElementGuid>591e0202-0613-4b60-8e42-84bd8ebec562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CP Asturias (ES)'])[1]/preceding::a[1]</value>
      <webElementGuid>c958b6b2-629e-470b-be10-90585acc5c70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CP Baleares (ES)'])[1]/preceding::a[2]</value>
      <webElementGuid>69bb6c05-ab71-4fbe-baff-94e18cd622bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CP Almeria (ES)']/parent::*</value>
      <webElementGuid>d4296796-f64b-484e-bf98-ff7430f87df5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[3]</value>
      <webElementGuid>1584bdf5-94b0-4987-8eeb-884a0baaf420</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/table/tbody/tr/td[4]/a</value>
      <webElementGuid>a634aebb-caa9-4e5a-849d-805117b97ce4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = 'CP Almeria (ES)' or . = 'CP Almeria (ES)')]</value>
      <webElementGuid>ce09fd23-6647-4990-ba79-95d4c472c288</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
