<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CP Almeria (ES)_1</name>
   <tag></tag>
   <elementGuidId>25d6732a-6e9b-4cdb-8914-50ce3c67f48e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='sendForm(124);']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b5781df3-39e3-4fdb-99fe-5990ca36b9c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>d70f1cbe-103b-4a85-80ca-dda0cd2467e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>sendForm(124);</value>
      <webElementGuid>af3a430d-81af-4da2-a6b0-1f6f1b79e03d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>decorate(this,0);</value>
      <webElementGuid>14b6dbe1-9873-478f-bddd-fff828e5522b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>decorate(this,1);</value>
      <webElementGuid>52b7960f-bbda-4035-b618-1e6aafbeaed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CP Almeria (ES)</value>
      <webElementGuid>113cf7ee-0d96-417d-b802-e51a9fa73c87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;m1&quot;)/div[@class=&quot;dealers-column&quot;]/div[@id=&quot;element-select2&quot;]/table[@id=&quot;dealerList&quot;]/tbody[1]/tr[1]/td[4]/a[1]</value>
      <webElementGuid>3c404b17-8133-45a9-bef2-d94885ec06b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='sendForm(124);']</value>
      <webElementGuid>a6f22c3a-e060-4b1b-8ead-648f39837f83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//table[@id='dealerList']/tbody/tr/td[4]/a)[3]</value>
      <webElementGuid>b0d8a448-fbba-402d-80c6-84cc28a23a4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'CP Almeria (ES)')]</value>
      <webElementGuid>05882c14-f5ef-4472-b4b3-c8d9de3e17a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CP Alicante (ES)'])[1]/following::a[1]</value>
      <webElementGuid>f03c8bf0-825a-4338-951a-63d64042c215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CP A Coruña (ES)'])[1]/following::a[2]</value>
      <webElementGuid>5238d88f-62ba-4f9d-8b4f-5875c3090507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CP Asturias (ES)'])[1]/preceding::a[1]</value>
      <webElementGuid>53043616-650c-48e3-b2a5-7daf683b66c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CP Baleares (ES)'])[1]/preceding::a[2]</value>
      <webElementGuid>e6a0f922-e6d7-45cb-ae76-6a68fb9e44b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CP Almeria (ES)']/parent::*</value>
      <webElementGuid>7fc7531e-6c5e-4d9c-b53f-1cbab175bf26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[3]</value>
      <webElementGuid>baa38939-81ed-40ed-bae4-e5596fda531f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/table/tbody/tr/td[4]/a</value>
      <webElementGuid>72286336-7de0-452a-bfcd-65dca1b9f062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = 'CP Almeria (ES)' or . = 'CP Almeria (ES)')]</value>
      <webElementGuid>c716c012-a3eb-4efa-b112-230b6e99e549</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
