<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Survey n8</name>
   <tag></tag>
   <elementGuidId>9ced93a6-341c-40d0-b76f-c6d9470df94c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#survey2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='survey2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>72e12e31-90cb-4788-b6e7-c08a134e5149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>a68a8617-0a5c-4c06-823a-05f80081a669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>launchTinyStartSurvey(8);</value>
      <webElementGuid>2fece69e-7a45-4d7d-9404-0feb42bbd805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>survey2</value>
      <webElementGuid>dda7e906-7b4f-42b9-a1ad-66717964f3db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-text-on</value>
      <webElementGuid>98193536-b91e-4fea-83ad-d51403694dde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Survey nº8 </value>
      <webElementGuid>4ab4d36a-17ea-49a3-9df1-ca83d44fc947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;survey2&quot;)</value>
      <webElementGuid>1a029846-43f0-4a8e-a52c-4ddc0f95728f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='survey2']</value>
      <webElementGuid>ad2b1812-959d-4ca0-92f3-0a71dc3aba4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='leftSide_ls2']/a</value>
      <webElementGuid>beec096c-7732-4d7b-8667-bf84a3dd5dce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Survey nº8')]</value>
      <webElementGuid>6d7b3540-ccb0-4d66-96b9-598a13e8b8e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Survey results'])[1]/following::a[1]</value>
      <webElementGuid>666f8e32-535e-4ee5-ac04-061c7acd59b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total surveys completed: 16'])[1]/following::a[2]</value>
      <webElementGuid>a871d969-7d7d-4382-acd0-6bc46b7e1e69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Survey nº8']/parent::*</value>
      <webElementGuid>6da98699-279a-4710-a519-db86379ff00b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[2]</value>
      <webElementGuid>02226856-ec6b-4f7d-90bb-3003d3b4da62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>fea9f26f-425e-4827-9f2c-9e9e2ed4fb0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and @id = 'survey2' and (text() = 'Survey nº8 ' or . = 'Survey nº8 ')]</value>
      <webElementGuid>da827d5d-df92-4235-af32-a4b02e6d9f7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
