<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next_1</name>
   <tag></tag>
   <elementGuidId>f0270f2c-a705-4199-8d91-a08bf81e3a22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ls-button-submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ls-button-submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1925adf3-4c2a-4374-af18-acc71073747a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ls-button-submit</value>
      <webElementGuid>a059006e-958c-48bf-9363-a1619065e3af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>52995b36-87c3-4191-8344-0c7e23e71f0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>movenext</value>
      <webElementGuid>822b8b58-c1b5-4ec2-95d7-e5165d6d939f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>move</value>
      <webElementGuid>771406e6-82c2-4b95-b7ce-3a9092292bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accesskey</name>
      <type>Main</type>
      <value>n</value>
      <webElementGuid>f786af9b-329a-4a73-b549-5728176c5025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nextButtonPBE ls-move-btn ls-move-next-btn ls-move-submit-btn action--ls-button-submit btn btn-lg btn-primary</value>
      <webElementGuid>60e731cb-58b8-4041-9838-f8001e689607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Next >>                                </value>
      <webElementGuid>562bd375-49ee-4ba6-b405-345355a11bc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ls-button-submit&quot;)</value>
      <webElementGuid>ea241afa-76eb-4093-9d71-5d6b75f479cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='ls-button-submit']</value>
      <webElementGuid>c6ee77ee-e11b-4822-8a1f-4fd866d919f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navigator-container']/div[2]/button</value>
      <webElementGuid>a27ba0e1-4a5c-46ab-bc4f-3af3b169bb9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Strongly agree'])[4]/following::button[1]</value>
      <webElementGuid>b0cb47ca-bc26-4a87-ba46-5c81398691d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Somewhat agree'])[4]/following::button[1]</value>
      <webElementGuid>bf1f7436-e587-4c24-9820-73e92d0b3b4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'ls-button-submit', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>968582d7-4860-493e-b2d9-2ad73806d670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Next >>']/parent::*</value>
      <webElementGuid>13d31ef2-9ff6-4d5d-9a9b-c397384cf878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>2125f71c-7c56-47fd-ad72-8004633eb188</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'ls-button-submit' and @type = 'submit' and @name = 'move' and (text() = '
                                    Next >>                                ' or . = '
                                    Next >>                                ')]</value>
      <webElementGuid>82858f30-f29c-45c8-aecf-04d164c33426</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
