<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Send</name>
   <tag></tag>
   <elementGuidId>d7b6fe7b-ab1f-42bb-88c5-ebd443b03242</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ls-button-submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ls-button-submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>84c7cd9a-cdae-47b8-b071-9d40b648985a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ls-button-submit</value>
      <webElementGuid>72b5388c-83d7-4578-b88a-d14efe95551e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>12336a42-ccdf-4f99-b330-4dc5c614b987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>movenext</value>
      <webElementGuid>3097a175-a97c-4280-9ca2-00eb394ae5ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>move</value>
      <webElementGuid>5e236f2d-0eb3-408e-888d-e75c08431e4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accesskey</name>
      <type>Main</type>
      <value>n</value>
      <webElementGuid>ff9764d1-5ab0-4772-8fb4-7bb91ce531a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nextButtonPBE ls-move-btn ls-move-next-btn ls-move-submit-btn action--ls-button-submit btn btn-lg btn-primary</value>
      <webElementGuid>860411c4-ce55-4ffb-b5d2-b7fa3a3d831d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Send                                </value>
      <webElementGuid>cf08bb92-782f-423a-b4bf-327084600153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ls-button-submit&quot;)</value>
      <webElementGuid>b6e78e2e-4e4d-465e-a139-d2e9da50a714</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='ls-button-submit']</value>
      <webElementGuid>1c487e64-2074-4661-84d5-022ac2cfd7bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navigator-container']/div[2]/button</value>
      <webElementGuid>c0e9e826-295d-4ed7-be3f-c51f8975b76e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&lt;&lt; Back'])[1]/following::button[1]</value>
      <webElementGuid>d74b3a46-6b0f-4ee6-81c3-b12fd0c39d7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SQ 5'])[1]/following::button[2]</value>
      <webElementGuid>568b2c33-e72f-47e9-b7eb-18e16608f8a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'ls-button-submit', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>2543c1a8-59ec-4539-b0f0-f636ef926c26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Send']/parent::*</value>
      <webElementGuid>79eb9db5-4ae5-499c-a69f-4997b16ea70e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>725293ec-1eda-45a1-9fef-b47b13799445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'ls-button-submit' and @type = 'submit' and @name = 'move' and (text() = '
                                    Send                                ' or . = '
                                    Send                                ')]</value>
      <webElementGuid>41170b2b-7aca-4e6f-8700-eaf4d1d30b22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
