<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_We have to implement these new job ro_529000</name>
   <tag></tag>
   <elementGuidId>6a62aa93-d38f-4e95-91bc-cad1a16edd8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;question-56&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='question-56']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d1ae8549-4bd2-4182-9f09-5466649ff35e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>740fa010-53b3-4779-955a-0a85b78875e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>question-56</value>
      <webElementGuid>afbbaf8e-f2f3-48f4-8a51-9d0ad019f6f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>06210724-5edd-41dd-bd44-13de319c9346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;limesurvey&quot;)/div[@id=&quot;group-3&quot;]/div[@class=&quot;group-container  space-col&quot;]/div[@id=&quot;question879&quot;]/div[@class=&quot;answer-container col-xs-12&quot;]/table[@class=&quot;ls-answers subquestion-list questions-list radio-array table table-bordered table-hover table-array-radio&quot;]/tbody[1]/tr[@class=&quot;pbe-question answers-list radio-list ls-odd&quot;]/td[@class=&quot;answer_cell_1 answer-item radio-item&quot;]/input[1]</value>
      <webElementGuid>b58c115a-1db2-477c-aab7-f0b4996945ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='question-56']</value>
      <webElementGuid>d69b13d8-c2bf-44c1-90b0-d9db552bcd45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='question879']/div[2]/table/tbody/tr[3]/td/input</value>
      <webElementGuid>6a8c7aa9-9ece-458e-8927-9514acca89d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/input</value>
      <webElementGuid>26e3f287-e392-439e-a027-f022d7eaf5f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'question-56']</value>
      <webElementGuid>e8e8911e-f542-49e2-b527-028f2c00bbcb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
