<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_I am well informed about the contents_e03153</name>
   <tag></tag>
   <elementGuidId>3d35c7be-0648-453a-99fa-12a6e478eb09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;question-81&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='question-81']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e1a3393b-73e4-4b20-b2fb-68eeb3e5ea1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>7d6d9a6e-b6bd-4d78-854b-f14d49c2d4e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>question-81</value>
      <webElementGuid>feb94f0d-2739-4de5-9026-65c7be9d15ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6c0e2853-a7da-47c2-b380-63aaeaa89885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;limesurvey&quot;)/div[@id=&quot;group-3&quot;]/div[@class=&quot;group-container  space-col&quot;]/div[@id=&quot;question879&quot;]/div[@class=&quot;answer-container col-xs-12&quot;]/table[@class=&quot;ls-answers subquestion-list questions-list radio-array table table-bordered table-hover table-array-radio&quot;]/tbody[1]/tr[@class=&quot;pbe-question answers-list radio-list ls-even&quot;]/td[@class=&quot;answer_cell_1 answer-item radio-item&quot;]/input[1]</value>
      <webElementGuid>c4586ce4-d0c5-40b7-8239-b76792b27087</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='question-81']</value>
      <webElementGuid>9d401184-29ba-4207-8d1b-f246c32b795a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='question879']/div[2]/table/tbody/tr[4]/td/input</value>
      <webElementGuid>20c93909-08a5-4741-8e7b-20d3d136216b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/input</value>
      <webElementGuid>2bc120ca-5c56-4d4a-b9ba-0052742d6aad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'question-81']</value>
      <webElementGuid>8d56173a-e1d4-44e7-8d3d-49254e0aa37f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
