<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_I need training measures to successfu_a8276f</name>
   <tag></tag>
   <elementGuidId>0d07b10f-85fd-435f-9d66-b3bfba60a8f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;question-62&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='question-62']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>76eda75a-95fc-4da5-910f-ab4daa5d86cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>6891ab76-c95b-4585-8a55-da94c7f1a180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>question-62</value>
      <webElementGuid>51c082aa-4f09-4c82-9c83-b0367a5302db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>30420979-b753-4f80-a917-e015df794a14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;limesurvey&quot;)/div[@id=&quot;group-3&quot;]/div[@class=&quot;group-container  space-col&quot;]/div[@id=&quot;question879&quot;]/div[@class=&quot;answer-container col-xs-12&quot;]/table[@class=&quot;ls-answers subquestion-list questions-list radio-array table table-bordered table-hover table-array-radio&quot;]/tbody[1]/tr[@class=&quot;pbe-question answers-list radio-list ls-even&quot;]/td[@class=&quot;answer_cell_1 answer-item radio-item&quot;]/input[1]</value>
      <webElementGuid>40e230ce-512e-497b-b3bf-5d2cf5736ef2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='question-62']</value>
      <webElementGuid>88b6d827-7227-4506-b183-ee13ae686fd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='question879']/div[2]/table/tbody/tr[2]/td/input</value>
      <webElementGuid>35a67bce-a013-4f03-b206-16a6e19822a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/input</value>
      <webElementGuid>c687f073-6966-416b-a536-b528212d7d9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'question-62']</value>
      <webElementGuid>d745a6c0-d1f5-469a-8f15-1c550eeb217b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
