<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_I am not concerned about the changes _e2bb80</name>
   <tag></tag>
   <elementGuidId>b5bf8482-74f9-4068-a13f-57235034aa5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;question-87&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='question-87']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>124494b7-3424-499b-bba1-a4c06325a2e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>861638d0-a737-4622-a284-ada63b77b95e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>question-87</value>
      <webElementGuid>9aadaac2-dac2-4c55-879c-0a496d7e77de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>76114fcf-7dd7-41d5-9206-24f98bfe98b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;limesurvey&quot;)/div[@id=&quot;group-3&quot;]/div[@class=&quot;group-container  space-col&quot;]/div[@id=&quot;question879&quot;]/div[@class=&quot;answer-container col-xs-12&quot;]/table[@class=&quot;ls-answers subquestion-list questions-list radio-array table table-bordered table-hover table-array-radio&quot;]/tbody[1]/tr[@class=&quot;pbe-question answers-list radio-list ls-odd&quot;]/td[@class=&quot;answer_cell_1 answer-item radio-item&quot;]/input[1]</value>
      <webElementGuid>c2aa875d-a5ce-4e3d-b53b-e5cceb17c39b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='question-87']</value>
      <webElementGuid>1ab21e7a-93d8-42e9-9195-550870e4dc75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='question879']/div[2]/table/tbody/tr[5]/td/input</value>
      <webElementGuid>5f0574e3-e73c-4a8e-98bc-27f3baa7168e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td/input</value>
      <webElementGuid>af533865-4db2-4b26-824b-5498bab0d9d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'question-87']</value>
      <webElementGuid>30bfaf2d-9105-4d40-93f6-27f6b249f0a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
