<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_M1                    M2            _7fab48</name>
   <tag></tag>
   <elementGuidId>1ad52e6c-24e0-4aa3-b77d-969d4e0dd7c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='selectSurveyModel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#selectSurveyModel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b093fe8a-12a1-45bb-9450-3f57d55fe0ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>languages</value>
      <webElementGuid>97bebbe3-b287-4fe7-a086-00646f9667af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectSurveyModel</value>
      <webElementGuid>16dd7b57-0d57-4dd9-a739-05573082bb80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    M1
                    M2
                                            M3
                        M4
                                            M5
                        M6
                                            M7
                        M8
                                    </value>
      <webElementGuid>cce715b7-630e-4a84-9dfd-2a65a2407629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectSurveyModel&quot;)</value>
      <webElementGuid>179d1779-d63e-4e65-b47e-41b8c119b216</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='selectSurveyModel']</value>
      <webElementGuid>a43c1b3c-e08d-4a96-ad64-7c5b97b8593f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create. Future. Performance.'])[1]/following::select[1]</value>
      <webElementGuid>75ddf028-fa4a-4c60-825a-efa80ecc7990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Porsche Business Excellence'])[1]/following::select[1]</value>
      <webElementGuid>d612567c-878d-4305-9ae1-1a12061406c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort by:'])[1]/preceding::select[1]</value>
      <webElementGuid>3ca55e30-0924-46bf-b855-c2d96790a218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/preceding::select[1]</value>
      <webElementGuid>69fa13c6-82dc-4f93-b535-20c1b94abf1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>fe75bd88-8a95-44f4-b7e1-792bbcdba627</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'languages' and @id = 'selectSurveyModel' and (text() = '
                    M1
                    M2
                                            M3
                        M4
                                            M5
                        M6
                                            M7
                        M8
                                    ' or . = '
                    M1
                    M2
                                            M3
                        M4
                                            M5
                        M6
                                            M7
                        M8
                                    ')]</value>
      <webElementGuid>3a43d2dc-d164-4d5c-ac77-96d437ac2051</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
