<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_M1                    M2            _7fab48</name>
   <tag></tag>
   <elementGuidId>1ad52e6c-24e0-4aa3-b77d-969d4e0dd7c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selectSurveyModel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='selectSurveyModel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>955e8152-601e-4bd4-9d98-f52d6efff8a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>languages</value>
      <webElementGuid>bd1363a6-f893-40f1-9c00-3873cdd58d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectSurveyModel</value>
      <webElementGuid>9a11ddcf-429c-435f-8ec8-75be4f2c6d14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    M1
                    M2
                                            M3
                        M4
                                            M5
                        M6
                                            M7
                        M8
                                    </value>
      <webElementGuid>bb742f05-abf4-451c-aca8-bf65d1b6c0e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectSurveyModel&quot;)</value>
      <webElementGuid>8e6313a5-8102-4dfa-9586-5bf6c422a530</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='selectSurveyModel']</value>
      <webElementGuid>e16d0961-5d5c-46d2-aa2e-13ee8b39d297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create. Future. Performance.'])[1]/following::select[1]</value>
      <webElementGuid>501a5b82-0bd7-4aed-a3f9-b35104e4b76b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Porsche Business Excellence'])[1]/following::select[1]</value>
      <webElementGuid>ee00192e-ea35-4e12-a451-d8121c5ee5c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort by:'])[1]/preceding::select[1]</value>
      <webElementGuid>d9a86eff-a3e8-431d-9d6f-e11f858adbf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/preceding::select[1]</value>
      <webElementGuid>33aeff86-c3d3-46e8-8653-738a80fc54cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>5dacd39d-b397-4534-ac08-0cd0ed47d3c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'languages' and @id = 'selectSurveyModel' and (text() = '
                    M1
                    M2
                                            M3
                        M4
                                            M5
                        M6
                                            M7
                        M8
                                    ' or . = '
                    M1
                    M2
                                            M3
                        M4
                                            M5
                        M6
                                            M7
                        M8
                                    ')]</value>
      <webElementGuid>db140ab5-84c5-4207-96a5-5f18f6bd0fbb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
