<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_M1                    M2            _7fab48</name>
   <tag></tag>
   <elementGuidId>1ad52e6c-24e0-4aa3-b77d-969d4e0dd7c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selectSurveyModel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='selectSurveyModel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>85f668e0-21de-4deb-b875-0c7de1d4b62a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>languages</value>
      <webElementGuid>4bc7d729-baa6-41b4-97ae-04dd060e4c93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectSurveyModel</value>
      <webElementGuid>4bba510f-242b-4ad3-a90f-b374a4bca76e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    M1
                    M2
                                            M3
                        M4
                                            M5
                        M6
                                            M7
                        M8
                                    </value>
      <webElementGuid>d60bd3c4-aa02-4819-9de3-93a8b82288a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectSurveyModel&quot;)</value>
      <webElementGuid>4e7e5488-0c15-4bac-b723-77cf41dad72d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='selectSurveyModel']</value>
      <webElementGuid>06c48eaa-44e3-4c65-aa36-0f1b067ca504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create. Future. Performance.'])[1]/following::select[1]</value>
      <webElementGuid>a56e88b5-5f8d-4499-be3b-95b58f8d71c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Porsche Business Excellence'])[1]/following::select[1]</value>
      <webElementGuid>556be157-9357-49c6-9591-4f969eef3a6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort by:'])[1]/preceding::select[1]</value>
      <webElementGuid>ec2578d9-0092-4fd6-ae24-d5dc420e7cc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/preceding::select[1]</value>
      <webElementGuid>03eb6f6c-da5a-4a2d-842d-fb44163402bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>cfeab446-e43a-4019-837b-38a7469b3cbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'languages' and @id = 'selectSurveyModel' and (text() = '
                    M1
                    M2
                                            M3
                        M4
                                            M5
                        M6
                                            M7
                        M8
                                    ' or . = '
                    M1
                    M2
                                            M3
                        M4
                                            M5
                        M6
                                            M7
                        M8
                                    ')]</value>
      <webElementGuid>458df909-e121-4d57-ae15-986184afa46d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
